
import type { Metadata } from 'next';
import { getAllPerformanceSignals } from '@/app/actions';
import PerformanceClientPage from './performance-client-page';

export const metadata: Metadata = {
  title: 'Historical Performance | ProfitScout',
  description: 'Explore the full historical performance of every options signal generated by the ProfitScout AI engine. Full transparency on our wins and losses.',
};

export default async function PerformancePage() {
    const allSignals = await getAllPerformanceSignals();

    return (
        <div className="space-y-8">
            <header className="text-center">
                <h1 className="text-4xl sm:text-5xl font-bold font-headline tracking-tight">
                    Signal Performance History
                </h1>
                <p className="mt-4 max-w-3xl mx-auto text-lg text-muted-foreground">
                    This is our complete, transparent archive of every signal our AI has generated. We believe in showing our work—both wins and losses.
                </p>
            </header>
            
            <PerformanceClientPage signals={allSignals} />

        </div>
    );
}
