
import type { Metadata } from 'next';
import { getAllPerformanceSignals } from '@/app/actions';
import PerformanceClientPage from './performance-client-page';
import { Card, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import Link from 'next/link';
import { ArrowRight } from 'lucide-react';
import { UserNav } from '@/components/auth/user-nav';

export const metadata: Metadata = {
  title: 'AI Options Signal Performance History | GammaRips',
  description: 'Review the complete, transparent performance history of every AI-generated options signal from GammaRips. See our wins and losses, updated daily.',
};

export default async function PerformancePage() {
    const allSignals = await getAllPerformanceSignals();

    const softwareSchema = {
        "@context": "https://schema.org",
        "@type": "SoftwareApplication",
        "name": "GammaRips Performance History",
        "description": "View the complete historical performance of every options signal generated by GammaRips's AI engine.",
        "applicationCategory": "FinancialApplication",
        "operatingSystem": "Web",
         "offers": {
            "@type": "Offer",
            "price": "19.00",
            "priceCurrency": "USD"
        }
    };

    return (
        <>
            <script
                type="application/ld+json"
                dangerouslySetInnerHTML={{ __html: JSON.stringify(softwareSchema) }}
            />
            <div className="space-y-8">
                <header className="text-center">
                    <h1 className="text-4xl sm:text-5xl font-bold font-headline tracking-tight">
                        The Rip Archive
                    </h1>
                    <p className="mt-4 max-w-3xl mx-auto text-lg text-muted-foreground">
                        This is the complete ledger of every Call and Put contract our engine has flagged. We show the work. We post the wins, the losses, and the flat trades. This is live data. It is not a cherry-picked highlight reel. Click any trade to view the full analysis.
                    </p>
                </header>
                
                <PerformanceClientPage signals={allSignals} />

                <div className="text-center">
                    <Card className="inline-block bg-primary/10 border-primary/20">
                        <CardContent className="p-6">
                            <h3 className="text-xl font-semibold font-headline">Get the Daily Playbook</h3>
                            <p className="text-muted-foreground mt-2 mb-4 max-w-md mx-auto">
                                Become a Ripper to get full access to our daily ranked Call & Put contracts. Unlock the interactive dashboard and the complete AI analysis behind every trade.
                            </p>
                            <Button asChild size="lg">
                                <Link href="/dashboard">
                                    Become a Ripper ($19/mo) <ArrowRight className="ml-2 h-5 w-5"/>
                                </Link>
                            </Button>
                            <p className="text-xs text-muted-foreground mt-3">Billed monthly. Cancel anytime. 7-day money-back guarantee on your first month.</p>
                        </CardContent>
                    </Card>
                </div>
            </div>
        </>
    );
}

