
import type { Metadata } from 'next';
import { getAllPerformanceSignals } from '@/app/actions';
import PerformanceClientPage from './performance-client-page';
import { Card, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import Link from 'next/link';
import { ArrowRight } from 'lucide-react';

export const metadata: Metadata = {
  title: 'Historical Performance | ProfitScout',
  description: 'Explore the full historical performance of every options signal generated by the ProfitScout AI engine. Full transparency on our wins and losses.',
};

export default async function PerformancePage() {
    const allSignals = await getAllPerformanceSignals();

    const softwareSchema = {
        "@context": "https://schema.org",
        "@type": "SoftwareApplication",
        "name": "ProfitScout",
        "description": "View the complete historical performance of every options signal generated by ProfitScout's AI engine.",
        "applicationCategory": "FinancialApplication",
        "operatingSystem": "Web",
         "offers": {
            "@type": "Offer",
            "price": "19.00",
            "priceCurrency": "USD"
        }
    };

    return (
        <>
            <script
                type="application/ld+json"
                dangerouslySetInnerHTML={{ __html: JSON.stringify(softwareSchema) }}
            />
            <div className="space-y-8">
                <header className="text-center">
                    <h1 className="text-4xl sm:text-5xl font-bold font-headline tracking-tight">
                        Signal Performance History
                    </h1>
                    <p className="mt-4 max-w-3xl mx-auto text-lg text-muted-foreground">
                        This is our complete, transparent archive of every signal our AI has generated. We believe in showing our work—both wins and losses.
                    </p>
                </header>
                
                <PerformanceClientPage signals={allSignals} />

                <div className="text-center">
                    <Card className="inline-block bg-primary/10 border-primary/20">
                        <CardContent className="p-6">
                            <h3 className="text-xl font-semibold font-headline">Ready to Get Started?</h3>
                            <p className="text-muted-foreground mt-2 mb-4">
                                Sign up for a free trial to get daily setups and access to the interactive dashboard.
                            </p>
                            <Button asChild size="lg">
                                <Link href="/dashboard">
                                    Start Your Free Trial <ArrowRight className="ml-2 h-5 w-5"/>
                                </Link>
                            </Button>
                        </CardContent>
                    </Card>
                </div>
            </div>
        </>
    );
}
