import {
    Accordion,
    AccordionContent,
    AccordionItem,
    AccordionTrigger,
} from "@/components/ui/accordion"

export const faqs = [
  {
    question: "What is The Overnight Edge?",
    answer: "The Overnight Edge is an institutional options flow scanner that analyzes activity across 5,230+ tickers every night. We surface what smart money did overnight — before the market opens."
  },
  {
    question: "How are signals scored?",
    answer: "Each signal is scored 1-10 based on institutional conviction indicators: new options positioning size, number of active strike prices, volume-to-open-interest ratio, and directional flow imbalance (call vs put dollar flow)."
  },
  {
    question: "What do I get with a free account?",
    answer: "Free users see daily signal previews including ticker, score, direction, percent move, and positioning size. You also get access to daily market themes and the public reports archive."
  },
  {
    question: "What does the $49/mo subscription include?",
    answer: "The Overnight Edge subscription unlocks the full AI-generated trade thesis for each signal, recommended contracts with specific strikes and expiries, key support/resistance levels, and detailed technical and news analysis."
  },
  {
    question: "What is The War Room ($149/mo)?",
    answer: "The War Room includes everything in The Overnight Edge plus real-time flow alerts via WhatsApp, priority access to the highest-conviction signals, and direct access to our analyst for questions."
  },
  {
    question: "When are signals delivered?",
    answer: "Our scanner runs at approximately 4:00 AM EST. Enriched signals are available on gammarips.com before the market opens at 9:30 AM EST."
  },
  {
    question: "Is this financial advice?",
    answer: "No. The Overnight Edge provides institutional flow data and AI-generated analysis for informational purposes only. All trading decisions are yours. We track our signals publicly so you can evaluate our accuracy, but past performance does not guarantee future results."
  },
  {
    question: "Can I cancel anytime?",
    answer: "Yes. All subscriptions are month-to-month with no contracts. Cancel anytime from your account page."
  },
  {
    question: "Who runs GammaRips?",
    answer: "GammaRips was founded by Evan Parra (ML engineer and data architect) and is operated by GammaMolt, an AI-powered trading analyst. Every signal is generated by our automated pipeline and tracked publicly."
  },
];

export default function Faq() {
    return (
        <Accordion type="single" collapsible className="w-full mt-12">
            {faqs.map((faq, i) => (
                <AccordionItem key={i} value={`item-${i}`}>
                    <AccordionTrigger>{faq.question}</AccordionTrigger>
                    <AccordionContent>
                        {faq.answer}
                    </AccordionContent>
                </AccordionItem>
            ))}
        </Accordion>
    )
}
